### ISSUE TITLE
Reunião para discutir sobre o Pyladies Conf

### ISSUE THREAD

**Issue by talitarossari** [pyladies-brazil/organization#13]
Temos que discutir local, preços, ingressos, questão de futuros.

Criei um Doodle para encontrarmos uma data ótima para todas as interessadas: https://doodle.com/poll/y6cg2dzadw4veqm7

**Comment by talitarossari** [comment]
Meninas, "fechei" o Doodle aqui, e o dia e hora com mais votação que a @pgrangeiro pode participar é na Segunda dia 16, das 20hrs as 22hrs.
Fechando a data, gostaria de saber se alguem pode puxar por mim a reunião.
@taniaa, @camilaavilarinho, @barmvicente

**Comment by barmvicente** [comment]
Eu posso @talitarossari . Podemos conversar antes para você me dizer a pauta?

**Comment by talitarossari** [comment]
@barmvicente, a data foi mudada para dia 27/10 as 20hrs.
Espero que consiga participar!

**Comment by talitarossari** [comment]
Reunião atualizada para dia 02/11 (feriado)

**Comment by letuche** [comment]
Confirmo dia 2/11. Permanece às 20h?

**Comment by talitarossari** [comment]
@letuche, permanece sim!

**Comment by deboraazevedo** [comment]
Ata da reunião https://docs.google.com/document/d/1QX9FCoxxezLa8D4Hmwk09zyVtqzBMLH9VArIRMExK3I/edit?usp=sharing

**Comment by deboraazevedo** [comment]
Link para o hangouts https://hangouts.google.com/call/DQrpIXuNqz_YD1iCzsOzAAEE

**Comment by deboraazevedo** [comment]
Pauta modificada - apenas com acesso de visualização https://docs.google.com/document/d/1QX9FCoxxezLa8D4Hmwk09zyVtqzBMLH9VArIRMExK3I/edit?usp=sharing

**Comment by rsip22** [comment]
Hmm então foi realizada.
