### ISSUE TITLE
Organizar uma equipe de revisão para os PRs do site

### ISSUE THREAD

**Issue by rsip22** [pyladies-brazil/organization#16]
Acho que seria importante ter isso organizado e documentado em algum lugar:

- Quem são as pessoas que podem revisar PRs do site PyLadies Brasil?
- Com que frequência podem fazê-lo (se atende as necessidades atuais ou se precisa mais gente)?
- Como fazer parte dessa equipe?

**Comment by rsip22** [comment]
Agora vi que tem uma tentativa disso sendo feita através de issue do repositório do site. Ainda assim, acho que isso deveria ser documentado de forma geral posteriormente, para todos repositórios PyLadies.

https://github.com/pyladies-brazil/br-pyladies-pelican/issues/140

**Comment by jtemporal** [comment]
acho que a intenção da pyladies-brazil/br-pyladies-pelican#140 é documentar o processo de revisão de PRs...

Acho q a definição de um time de revisão de PRs é uma boa 😉

hoje todas com acesso a organização pode revisar e aprovar PRs e que me lembre o único combinado (combinado na python brasil de 2016) é testar se staging ta okay antes de dar merge pra garantir que o site não quebre. Desde de lá mudamos o CI e também o fluxo de deploy para staging mas o processo de revisão pra mim pelo menos continua o mesmo.

**Comment by jtemporal** [comment]
ps.: esqueci de comentar mas to disponível pra dedicar tempo toda semana para isso =)

**Comment by biancarosa** [comment]
Resolvemos isso com o @pyladies-brazil/tech-team ;)
