### ISSUE TITLE
Criar README do repositório 

### ISSUE THREAD

**Issue by rsip22** [pyladies-brazil/organization#4]
O repositório abre sem nada. Seria importante criar um README explicando para que ele serve e como as pessoas podem contribuir.

**Comment by rebecabordini** [comment]
Eu posso fazer.

**Comment by deboraazevedo** [comment]
@rsip22 @rebecabordini tava vendo as issues, vi que isso estava pendente e acabei de criar o README. Vou fechar essa issue,  ok?

**Comment by jtemporal** [comment]
> Vou fechar essa issue, ok?

Fechando
