### ISSUE TITLE
Criar publieditoriais da campanha PyBR[13]

### ISSUE THREAD

**Issue by pgrangeiro** [pyladies-brazil/organization#8]
Uma das recompensas da campanha PyBR[13] ... a um publieditorial em duas versões: facebook (resumida) e site (completa). Ainda falta criar dois publieditories para os financiadores da campanha. Eles devem ser criado até o dia 13/10. Quem quiser mais informações sobre o assunto basta me contactar.

**Comment by talitarossari** [comment]
@letuche, você que escreve bem, consegue dar uma mão?

**Comment by pgrangeiro** [comment]
A @letuche já está ajudando. Falta só um publieditorial.
